Sneak peek: Recipe app
MenendezON/Recipe-app pull request #28
Opened 2023-11-23 21:48 UTC by MenendezON

Sneak peek: Recipe app
This pull request is about the Recipe-App project. We implemented:
- [ ] Login page and registration page using devise.
- [ ]  Recipes list:
- [ ]  Public recipe list
- [ ]  Recipe details
- [ ]  Make sure there are no N+1 queries happening.
- [ ]  Create a navigation menu that allows users to open all of the pages you created.
- [ ]  Write unit and integration tests
- [ ]  Food list
- [ ]  General shopping list view

2023-11-23 23:59 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @MenendezON, @Wils-FOURR-speed, @malikhaiderkhan 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Used validations for models. :heavy_check_mark: 
- Used Devise gem for authentication :heavy_check_mark: 
- Created all tables with correct columns and data type :heavy_check_mark: 
- Secured app from n+1 problems :heavy_check_mark: 
- Set up associations between models. :heavy_check_mark: 
- Good design :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-23 23:59 UTC, tresorsawasawa commented on app/views/partials/_navbar.html.erb
> +      <% end %>
- [ ] Good job by creating a navigation menu that allows to open some pages you created. However, as it required for the project, kindly ensure that Create all of the pages you created have a link in the nav-menu. Right now, I noticed that you miss link that opens the `Food list` and `Shopping list` page i.e `foods_path` and `shopping_lists_path`

2023-11-23 23:59 UTC, tresorsawasawa commented on app/views/partials/_navbar.html.erb
> +        </li>
- [ ] As required for the project the `app/views/foods/_form.html.erb` page to have a **add new food item** button that leads to the form that allows users to add new food, I think it would be better it you add it in `app/views/foods/_form.html.erb` page as it is showed in the given **[wirefame](https://github.com/microverseinc/curriculum-rails/raw/main/recipe-app/images/food_index.png)**.

2023-11-23 23:59 UTC, tresorsawasawa commented on app/views/foods/index.html.erb
> +      <% end %>
- [ ] As required for the project and for security reasons, even if the displayed foods list are owned by logged-in user, kindly ensure that the logged-in user is an owner in the delete action i.e. user can delete a food if he is the owner.

2023-11-23 23:59 UTC, tresorsawasawa commented on app/views/recipes/index.html.erb
> +                </button>
- [ ] As required for the project when clicking on a recipe item takes you to the recipe details page `/recipes/:id/` as shown in the given [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_food.png?raw=true), I think it would be better if you replace the `Show` button with that feature to match the given [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/recipe-app/images/recipe_index.png) from the requirements.

2023-11-23 23:59 UTC, tresorsawasawa commented on app/views/public_recipes/index.html.erb
> +          </button>
- [ ] As I mentioned the previous comment and as required for the project when clicking on a recipe item takes you to the recipe details page `/recipes/:id/` as shown in the given [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_food.png?raw=true), I think it would be better if you replace the `Show Details` button with that feature to match the given [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/recipe-app/images/recipe_index.png) from the requirements.

2023-11-23 23:59 UTC, tresorsawasawa commented on app/views/inventories/new.html.erb
> +      <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
- [ **OPTIONAL** ] For good user experience and to prevent inventories to have same description, I thing it would be better if you add a field in your form where user can add the inventory's ddescriprion

2023-11-23 23:59 UTC, tresorsawasawa commented on app/views/recipes/show.html.erb
> +
- [ ] As required for the project, kindly ensure that user can create a shopping list as in the [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_food_shopping_list.png?raw=true). Right now, your application doesn't accept create a shopping list as it always displays the alert message after clicking the **Generate** button.
![ksnip_20231123-184335](https://github.com/MenendezON/Recipe-app/assets/83042742/c56695ab-076a-4d71-842a-0048409d869b)

2023-11-23 23:59 UTC, tresorsawasawa commented on spec/models/user_spec.rb
> +
- [ ] As required for the project, kindly ensure that you also wrote Integration tests for your views by using capybara gem and all of them should pass.

2023-11-24 18:54 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @TEAM 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉


## Highlight 👍 
Made sugged changes

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-24 20:30 UTC, merged